### ISSUE TITLE
Community Guideline

### ISSUE THREAD

**Issue by mingzehuang** [s-abbas/robnptests#1]
Hi, @s-abbas,
here is a template to create [community guildline](https://github.com/mingzehuang/latentcor/blob/master/CONTRIBUTING.md) which include how to contribute to the software:)

**Comment by s-abbas** [comment]
Hi @mingzehuang,

thanks again for the template. We added the contribution guidelines to our repository.

**Comment by mingzehuang** [comment]
Great thanks @s-abbas !
